name: Check tag

on:
  workflow_dispatch:
    branches:
      - main

jobs:

  check-tag:
    name: Check tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Create tag and changelog
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          custom_release_rules: chore:patch:Chores
