name: Release

on:
  workflow_dispatch:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  tag:
    name: Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.tag.outputs.new_version }}
      changelog: ${{ steps.tag.outputs.changelog }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Create tag and changelog
        uses: mathieudutour/github-tag-action@v6.2
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: chore:patch:Chores

  container:
    name: Publish container
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.tag.outputs.tag }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: true
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ needs.tag.outputs.tag }}
            org.opencontainers.image.revision=${{ github.sha }}

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - tag
      - container
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          name: Release ${{ needs.tag.outputs.version }}
          body: |
            Changes in this release:
            ${{ needs.tag.outputs.changelog }}
            Docker image: ghcr.io/${{ github.repository }}:${{ needs.tag.outputs.tag }}
